const languages_list = [
    "1C",
    "4D",
    "ABNF",
    "Access logs",
    "Ada",
    "Arduino",
    "ARM assembler",
    "AVR assembler",
    "ActionScript",
    "Alan",
    "AngelScript",
    "Apache",
    "AppleScript",
    "Arcade",
    "AsciiDoc",
    "AspectJ",
    "AutoHotkey",
    "AutoIt",
    "Awk",
    "Axapta",
    "Bash",
    "Basic",
    "BNF",
    "Brainfuck",
    "C#",
    "C",
    "C++",
    "C/AL",
    "Cache Object Script",
    "CMake",
    "Coq",
    "CSP",
    "CSS",
    "Cap’n Proto",
    "Chaos",
    "Cisco CLI",
    "Clojure",
    "CoffeeScript",
    "CpcdosC+",
    "Crmsh",
    "Crystal",
    "Cypher (Neo4j)",
    "D",
    "DNS Zone file",
    "DOS",
    "Dart",
    "Delphi",
    "Diff",
    "Django",
    "Dockerfile",
    "dsconfig",
    "DTS (Device Tree)",
    "Dust",
    "Dylan",
    "EBNF",
    "Elixir",
    "Elm",
    "Erlang",
    "Excel",
    "Extempore",
    "F#",
    "FIX",
    "Fortran",
    "G-Code",
    "Gams",
    "GAUSS",
    "GDScript",
    "Gherkin",
    "GN for Ninja",
    "Go",
    "Grammatical Framework",
    "Golo",
    "Gradle",
    "Groovy",
    "HTML, XML",
    "HTTP",
    "Haml",
    "Handlebars",
    "Haskell",
    "Haxe",
    "Hy",
    "Ini, TOML",
    "Inform7",
    "IRPF90",
    "JSON",
    "Java",
    "JavaScript",
    "Jolie",
    "Kotlin",
    "LaTeX",
    "Leaf",
    "Lean",
    "Lasso",
    "Less",
    "LDIF",
    "Lisp",
    "LiveCode Server",
    "LiveScript",
    "Lua",
    "Makefile",
    "Markdown",
    "Mathematica",
    "Matlab",
    "Maxima",
    "Maya Embedded Language",
    "Mercury",
    "mIRC Scripting Language",
    "Mizar",
    "Mojolicious",
    "Monkey",
    "Moonscript",
    "N1QL",
    "NSIS",
    "Never",
    "Nginx",
    "Nim",
    "Nix",
    "Object Constraint Language",
    "OCaml",
    "Objective C",
    "OpenGL Shading Language",
    "OpenSCAD",
    "Oracle Rules Language",
    "Oxygene",
    "PF",
    "PHP",
    "Parser3",
    "Perl",
    "Plaintext",
    "Pony",
    "PostgreSQL & PL/pgSQL",
    "PowerShell",
    "Processing",
    "Prolog",
    "Properties",
    "Protocol Buffers",
    "Puppet",
    "Python",
    "Python profiler results",
    "Python REPL",
    "Q",
    "QML",
    "R",
    "Razor CSHTML",
    "ReasonML",
    "RenderMan RIB",
    "RenderMan RSL",
    "Roboconf",
    "Robot Framework",
    "RPM spec files",
    "Ruby",
    "Rust",
    "SAS",
    "SCSS",
    "SQL",
    "STEP Part 21",
    "Scala",
    "Scheme",
    "Scilab",
    "Shape Expressions",
    "Shell",
    "Smali",
    "Smalltalk",
    "SML",
    "Solidity",
    "Stan",
    "Stata",
    "Structured Text",
    "Stylus",
    "SubUnit",
    "Supercollider",
    "Svelte",
    "Swift",
    "Tcl",
    "Terraform (HCL)",
    "Test Anything Protocol",
    "Thrift",
    "TP",
    "Transact-SQL",
    "Twig",
    "TypeScript",
    "Unicorn Rails log",
    "VB.Net",
    "VBA",
    "VBScript",
    "VHDL",
    "Vala",
    "Verilog",
    "Vim Script",
    "x86 Assembly",
    "XL",
    "XQuery",
    "YAML",
    "Zephir"
];

export default languages_list;
