const languages_list = [
    { value: "1C", label: "1C" },
    { value: "4D", label: "4D" },
    { value: "ABNF", label: "ABNF" },
    { value: "Access logs", label: "Access logs" },
    { value: "Ada", label: "Ada" },
    { value: "Arduino", label: "Arduino" },
    { value: "ARM assembler", label: "ARM assembler" },
    { value: "AVR assembler", label: "AVR assembler" },
    { value: "ActionScript", label: "ActionScript" },
    { value: "Alan", label: "Alan" },
    { value: "AngelScript", label: "AngelScript" },
    { value: "Apache", label: "Apache" },
    { value: "AppleScript", label: "AppleScript" },
    { value: "Arcade", label: "Arcade" },
    { value: "AsciiDoc", label: "AsciiDoc" },
    { value: "AspectJ", label: "AspectJ" },
    { value: "AutoHotkey", label: "AutoHotkey" },
    { value: "AutoIt", label: "AutoIt" },
    { value: "Awk", label: "Awk" },
    { value: "Axapta", label: "Axapta" },
    { value: "Bash", label: "Bash" },
    { value: "Basic", label: "Basic" },
    { value: "BNF", label: "BNF" },
    { value: "Brainfuck", label: "Brainfuck" },
    { value: "C#", label: "C#" },
    { value: "C", label: "C" },
    { value: "C++", label: "C++" },
    { value: "C/AL", label: "C/AL" },
    { value: "Cache Object Script", label: "Cache Object Script" },
    { value: "CMake", label: "CMake" },
    { value: "Coq", label: "Coq" },
    { value: "CSP", label: "CSP" },
    { value: "CSS", label: "CSS" },
    { value: "Cap’n Proto", label: "Cap’n Proto" },
    { value: "Chaos", label: "Chaos" },
    { value: "Cisco CLI", label: "Cisco CLI" },
    { value: "Clojure", label: "Clojure" },
    { value: "CoffeeScript", label: "CoffeeScript" },
    { value: "CpcdosC+", label: "CpcdosC+" },
    { value: "Crmsh", label: "Crmsh" },
    { value: "Crystal", label: "Crystal" },
    { value: "Cypher (Neo4j)", label: "Cypher (Neo4j)" },
    { value: "D", label: "D" },
    { value: "DNS Zone file", label: "DNS Zone file" },
    { value: "DOS", label: "DOS" },
    { value: "Dart", label: "Dart" },
    { value: "Delphi", label: "Delphi" },
    { value: "Diff", label: "Diff" },
    { value: "Django", label: "Django" },
    { value: "Dockerfile", label: "Dockerfile" },
    { value: "dsconfig", label: "dsconfig" },
    { value: "DTS (Device Tree)", label: "DTS (Device Tree)" },
    { value: "Dust", label: "Dust" },
    { value: "Dylan", label: "Dylan" },
    { value: "EBNF", label: "EBNF" },
    { value: "Elixir", label: "Elixir" },
    { value: "Elm", label: "Elm" },
    { value: "Erlang", label: "Erlang" },
    { value: "Excel", label: "Excel" },
    { value: "Extempore", label: "Extempore" },
    { value: "F#", label: "F#" },
    { value: "FIX", label: "FIX" },
    { value: "Fortran", label: "Fortran" },
    { value: "G-Code", label: "G-Code" },
    { value: "Gams", label: "Gams" },
    { value: "GAUSS", label: "GAUSS" },
    { value: "GDScript", label: "GDScript" },
    { value: "Gherkin", label: "Gherkin" },
    { value: "GN for Ninja", label: "GN for Ninja" },
    { value: "Go", label: "Go" },
    { value: "Grammatical Framework", label: "Grammatical Framework" },
    { value: "Golo", label: "Golo" },
    { value: "Gradle", label: "Gradle" },
    { value: "Groovy", label: "Groovy" },
    { value: "HTML, XML", label: "HTML, XML" },
    { value: "HTTP", label: "HTTP" },
    { value: "Haml", label: "Haml" },
    { value: "Handlebars", label: "Handlebars" },
    { value: "Haskell", label: "Haskell" },
    { value: "Haxe", label: "Haxe" },
    { value: "Hy", label: "Hy" },
    { value: "Ini, TOML", label: "Ini, TOML" },
    { value: "Inform7", label: "Inform7" },
    { value: "IRPF90", label: "IRPF90" },
    { value: "JSON", label: "JSON" },
    { value: "Java", label: "Java" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "Jolie", label: "Jolie" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "LaTeX", label: "LaTeX" },
    { value: "Leaf", label: "Leaf" },
    { value: "Lean", label: "Lean" },
    { value: "Lasso", label: "Lasso" },
    { value: "Less", label: "Less" },
    { value: "LDIF", label: "LDIF" },
    { value: "Lisp", label: "Lisp" },
    { value: "LiveCode Server", label: "LiveCode Server" },
    { value: "LiveScript", label: "LiveScript" },
    { value: "Lua", label: "Lua" },
    { value: "Makefile", label: "Makefile" },
    { value: "Markdown", label: "Markdown" },
    { value: "Mathematica", label: "Mathematica" },
    { value: "Matlab", label: "Matlab" },
    { value: "Maxima", label: "Maxima" },
    { value: "Maya Embedded Language", label: "Maya Embedded Language" },
    { value: "Mercury", label: "Mercury" },
    { value: "mIRC Scripting Language", label: "mIRC Scripting Language" },
    { value: "Mizar", label: "Mizar" },
    { value: "Mojolicious", label: "Mojolicious" },
    { value: "Monkey", label: "Monkey" },
    { value: "Moonscript", label: "Moonscript" },
    { value: "N1QL", label: "N1QL" },
    { value: "NSIS", label: "NSIS" },
    { value: "Never", label: "Never" },
    { value: "Nginx", label: "Nginx" },
    { value: "Nim", label: "Nim" },
    { value: "Nix", label: "Nix" },
    {
        value: "Object Constraint Language",
        label: "Object Constraint Language"
    },
    { value: "OCaml", label: "OCaml" },
    { value: "Objective C", label: "Objective C" },
    { value: "OpenGL Shading Language", label: "OpenGL Shading Language" },
    { value: "OpenSCAD", label: "OpenSCAD" },
    { value: "Oracle Rules Language", label: "Oracle Rules Language" },
    { value: "Oxygene", label: "Oxygene" },
    { value: "PF", label: "PF" },
    { value: "PHP", label: "PHP" },
    { value: "Parser3", label: "Parser3" },
    { value: "Perl", label: "Perl" },
    { value: "Plaintext", label: "Plaintext" },
    { value: "Pony", label: "Pony" },
    { value: "PostgreSQL & PL/pgSQL", label: "PostgreSQL & PL/pgSQL" },
    { value: "PowerShell", label: "PowerShell" },
    { value: "Processing", label: "Processing" },
    { value: "Prolog", label: "Prolog" },
    { value: "Properties", label: "Properties" },
    { value: "Protocol Buffers", label: "Protocol Buffers" },
    { value: "Puppet", label: "Puppet" },
    { value: "Python", label: "Python" },
    { value: "Python profiler results", label: "Python profiler results" },
    { value: "Python REPL", label: "Python REPL" },
    { value: "Q", label: "Q" },
    { value: "QML", label: "QML" },
    { value: "R", label: "R" },
    { value: "Razor CSHTML", label: "Razor CSHTML" },
    { value: "ReasonML", label: "ReasonML" },
    { value: "RenderMan RIB", label: "RenderMan RIB" },
    { value: "RenderMan RSL", label: "RenderMan RSL" },
    { value: "Roboconf", label: "Roboconf" },
    { value: "Robot Framework", label: "Robot Framework" },
    { value: "RPM spec files", label: "RPM spec files" },
    { value: "Ruby", label: "Ruby" },
    { value: "Rust", label: "Rust" },
    { value: "SAS", label: "SAS" },
    { value: "SCSS", label: "SCSS" },
    { value: "SQL", label: "SQL" },
    { value: "STEP Part 21", label: "STEP Part 21" },
    { value: "Scala", label: "Scala" },
    { value: "Scheme", label: "Scheme" },
    { value: "Scilab", label: "Scilab" },
    { value: "Shape Expressions", label: "Shape Expressions" },
    { value: "Shell", label: "Shell" },
    { value: "Smali", label: "Smali" },
    { value: "Smalltalk", label: "Smalltalk" },
    { value: "SML", label: "SML" },
    { value: "Solidity", label: "Solidity" },
    { value: "Stan", label: "Stan" },
    { value: "Stata", label: "Stata" },
    { value: "Structured Text", label: "Structured Text" },
    { value: "Stylus", label: "Stylus" },
    { value: "SubUnit", label: "SubUnit" },
    { value: "Supercollider", label: "Supercollider" },
    { value: "Svelte", label: "Svelte" },
    { value: "Swift", label: "Swift" },
    { value: "Tcl", label: "Tcl" },
    { value: "Terraform (HCL)", label: "Terraform (HCL)" },
    { value: "Test Anything Protocol", label: "Test Anything Protocol" },
    { value: "Thrift", label: "Thrift" },
    { value: "TP", label: "TP" },
    { value: "Transact-SQL", label: "Transact-SQL" },
    { value: "Twig", label: "Twig" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Unicorn Rails log", label: "Unicorn Rails log" },
    { value: "VB.Net", label: "VB.Net" },
    { value: "VBA", label: "VBA" },
    { value: "VBScript", label: "VBScript" },
    { value: "VHDL", label: "VHDL" },
    { value: "Vala", label: "Vala" },
    { value: "Verilog", label: "Verilog" },
    { value: "Vim Script", label: "Vim Script" },
    { value: "x86 Assembly", label: "x86 Assembly" },
    { value: "XL", label: "XL" },
    { value: "XQuery", label: "XQuery" },
    { value: "YAML", label: "YAML" },
    { value: "Zephir", label: "Zephir" }
];

export default languages_list;
